import { motion, AnimatePresence } from "framer-motion";
import { UserPlus, Clock, Target, Users, AlertTriangle, FileText, X } from "lucide-react";
import { useState } from "react";

interface NewStakeholderContextProps {
  isVisible: boolean;
  onClose?: () => void;
}

interface ContextItem {
  type: "decision" | "project" | "team" | "risk";
  title: string;
  description: string;
  timestamp: string;
  relevance: "high" | "medium";
}

const contextItems: ContextItem[] = [
  {
    type: "decision",
    title: "API Migration Timeline",
    description: "Deadline moved from March 15 to February 28 at client request. Resource reallocation under discussion.",
    timestamp: "Updated 2 hrs ago",
    relevance: "high",
  },
  {
    type: "project",
    title: "SOC2 Compliance Audit",
    description: "Three critical findings overlap with migration work. Compliance team flagged as potential blocker.",
    timestamp: "Flagged yesterday",
    relevance: "high",
  },
  {
    type: "team",
    title: "Platform Team",
    description: "Led by Sarah Okafor. Currently at capacity, requesting 2 engineers from Mobile team.",
    timestamp: "5 members",
    relevance: "medium",
  },
  {
    type: "risk",
    title: "Resource Conflict",
    description: "Marcus Rivera has not approved engineer reallocation. Mobile roadmap may be impacted.",
    timestamp: "Pending resolution",
    relevance: "high",
  },
];

const typeIcons = {
  decision: Target,
  project: FileText,
  team: Users,
  risk: AlertTriangle,
};

const typeColors = {
  decision: "text-intent-decision bg-intent-decision/10 border-intent-decision/20",
  project: "text-intent-fyi bg-intent-fyi/10 border-intent-fyi/20",
  team: "text-primary bg-primary/10 border-primary/20",
  risk: "text-intent-risk bg-intent-risk/10 border-intent-risk/20",
};

const containerVariants = {
  hidden: { opacity: 0, scale: 0.95 },
  visible: { 
    opacity: 1, 
    scale: 1,
    transition: { staggerChildren: 0.08 }
  },
  exit: { opacity: 0, scale: 0.95 }
};

const itemVariants = {
  hidden: { opacity: 0, y: 8 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.3 } },
};

export default function NewStakeholderContext({ isVisible, onClose }: NewStakeholderContextProps) {
  const [dismissed, setDismissed] = useState<string[]>([]);

  if (!isVisible) return null;

  const visibleItems = contextItems.filter(item => !dismissed.includes(item.title));

  return (
    <motion.div
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      exit="exit"
      className="rounded-lg border border-primary/20 bg-primary/5 p-4 space-y-4"
    >
      <motion.div variants={itemVariants} className="flex items-start justify-between">
        <div className="flex items-center gap-2">
          <div className="p-1.5 rounded-lg bg-primary/15">
            <UserPlus className="w-4 h-4 text-primary" />
          </div>
          <div>
            <h2 className="font-heading text-sm font-semibold text-foreground">New Stakeholder Context</h2>
            <p className="text-[10px] text-muted-foreground">Instant onboarding view generated by JARVIS</p>
          </div>
        </div>
        {onClose && (
          <button
            onClick={onClose}
            className="p-1 rounded-md text-muted-foreground hover:text-foreground hover:bg-secondary transition-colors"
          >
            <X className="w-3.5 h-3.5" />
          </button>
        )}
      </motion.div>

      <motion.div variants={itemVariants} className="rounded-md bg-card border border-border p-3">
        <div className="flex items-center gap-2 mb-2">
          <Clock className="w-3.5 h-3.5 text-muted-foreground" />
          <span className="text-[10px] uppercase tracking-wider text-muted-foreground font-medium">
            What you need to know right now
          </span>
        </div>
        <p className="text-xs text-foreground leading-relaxed">
          You're joining during a critical period. The API migration deadline was just accelerated, 
          creating resource tensions between Platform and Mobile teams. A decision meeting is scheduled 
          for Thursday to resolve the conflict.
        </p>
      </motion.div>

      <motion.div variants={itemVariants} className="space-y-2">
        <div className="text-[10px] uppercase tracking-wider text-muted-foreground font-medium">
          Key Context ({visibleItems.length} items)
        </div>

        <AnimatePresence mode="popLayout">
          {visibleItems.map((item) => {
            const Icon = typeIcons[item.type];
            return (
              <motion.div
                key={item.title}
                layout
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, x: -8 }}
                className="rounded-md bg-card border border-border p-3"
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="flex items-start gap-2">
                    <div className={`p-1 rounded border ${typeColors[item.type]}`}>
                      <Icon className="w-3 h-3" />
                    </div>
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="text-xs font-medium text-foreground">{item.title}</span>
                        {item.relevance === "high" && (
                          <span className="text-[9px] px-1.5 py-0.5 rounded-full bg-intent-risk/10 text-intent-risk font-mono">
                            HIGH
                          </span>
                        )}
                      </div>
                      <p className="text-[11px] text-muted-foreground mt-0.5">{item.description}</p>
                      <span className="text-[10px] text-muted-foreground font-mono mt-1 inline-block">
                        {item.timestamp}
                      </span>
                    </div>
                  </div>
                  <button
                    onClick={() => setDismissed(prev => [...prev, item.title])}
                    className="p-0.5 rounded text-muted-foreground hover:text-foreground transition-colors flex-shrink-0"
                  >
                    <X className="w-3 h-3" />
                  </button>
                </div>
              </motion.div>
            );
          })}
        </AnimatePresence>
      </motion.div>

      <motion.div variants={itemVariants} className="flex items-center justify-between pt-2 border-t border-border">
        <span className="text-[10px] text-muted-foreground">
          Context generated from 12 signals over 48 hours
        </span>
        <button className="text-[10px] text-primary hover:text-primary/80 transition-colors font-medium">
          View full history →
        </button>
      </motion.div>
    </motion.div>
  );
}
